env:
  browser: true
  es6: true
  jest: true
extends: airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
parser: babel-eslint
plugins:
  - react
rules: {
  'react/jsx-uses-react': 1,
  'react/jsx-uses-vars': 1,
  'react/jsx-filename-extension': 0,
  'react/jsx-one-expression-per-line': 0,
  'react/react-in-jsx-scope': 1,
  'import/no-extraneous-dependencies': [error, { devDependencies: true }]
}
