defaults: &defaults
  docker:
    - image: circleci/node:10

version: 2

jobs:
  pre-build:
    working_directory: ~/project
    <<: *defaults
    steps:
      - checkout:
          path: ~/project/
      - attach_workspace:
          at: ~/project/

      - restore_cache:
          key: node-v2-{{ checksum "package.json" }}-{{ arch }}

      - run:
          name: Install dependencies
          command: npm i

      - save_cache:
          key: node-v2-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  lint:
    working_directory: ~/project
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/
      - run:
          name: Lint
          command: npm run lint

  test:
    working_directory: ~/project
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/
      - run:
          name: Test
          command: npm run test

  deploy:
    working_directory: ~/project
    <<: *defaults
    steps:
      - checkout:
          path: ~/project/
      - attach_workspace:
          at: ~/project/
      - add_ssh_keys:
          fingerprints:
            - "f9:68:22:93:9b:80:28:8a:d7:5b:cd:22:28:71:4f:c1"
      - run:
          name: Set git config
          command: |
            git config user.email "ci-build@vivaldi.ch"
            git config user.name "ci-build"
      - run:
          name: Deploy docs to gh-pages branch
          command: npm run deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - pre-build:
          filters:
            branches:
              only: master
      - lint:
          requires:
            - pre-build
      - test:
          requires:
            - lint
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master