version: 2

jobs:
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Test
          command: npm run test

  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Build docs
          command: npm run build

  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@vivaldi.ch"
            git config user.name "ci-build"
      - run:
          name: Deploy docs to gh-pages branch
          command: npm run deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - build
      - deploy:
        requires:
          - test
          - build
        filters:
          branches:
            only: master